/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma {
  int room_loadtimecount = 1;
  tile tiles_6[] = {
  };
  inst insts_6[] = {
{100510,60,112,96},  };
  roomstruct grd_rooms[1] = {
    //Room 6
    { 6, 0, "rm_7",  "",
      0xffcc66, true, roomcreate6,
      roomprecreate6,
      640, 480, 30,  false,  false, {
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { false,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false,   1,   16777215 },
      },      1, insts_6      ,0, tiles_6    },
  };
  
  int maxid = 100510 + 1;
  int maxtileid = 10000000 + 1;
} // Namespace enigma
int room_first = 6;
int room_last = 6;
