/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.


namespace enigma
{
  struct event_parent: object_collisions
  {
    virtual variant myevent_beforecollisionautomaticcollisionhandling()
    {
  ;
    return 0;
    }
    virtual variant myevent_beginstep()
    {
  {xprevious = x; yprevious = y; if (sprite_index != -1) image_index = fmod((image_speed < 0)?(sprite_get_number(sprite_index) + image_index - fmod(abs(image_speed),sprite_get_number(sprite_index))):(image_index + image_speed), sprite_get_number(sprite_index));}
    return 0;
    }
    virtual variant myevent_create() { return 0; } // No default Create code.
    inline virtual bool myevent_draw_subcheck() { return false; }
    virtual variant myevent_draw()
    {
  if (visible && sprite_index != -1) draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha);
    return 0;
    }
    virtual variant myevent_endstep()
    {
  { if (timeline_running && timeline_loop && timeline_speed!=0) loop_curr_timeline(); }
    return 0;
    }
    virtual variant myevent_localsweep()
    {
  enigma::propagate_locals(this);
    return 0;
    }
    virtual variant myevent_particlesystemsupdate()
    {
  ;
    return 0;
    }
    virtual variant myevent_step()
    {
  { if (timeline_running && timeline_speed!=0) advance_curr_timeline(); }
    return 0;
    }
    virtual void timeline_call_moment_script(int timeline_index, int moment_index) {
      switch (timeline_index) {
      }
    }
    //virtual void unlink() {} // This is already declared at the super level.
    virtual variant myevents_perf(int type, int numb) {return 0;}
    event_parent() {}
    event_parent(unsigned _x, int _y): object_collisions(_x,_y) {}
  };
}
